# THIS IS COPY / PASTED STRAIGHT OUT OF THE SINATRA .travis.yml:
# https://github.com/sinatra/sinatra/blob/v1.4.5/.travis.yml
# (added 2.2.0)
---
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx
  - jruby
  - jruby-head
  - ruby-head
matrix:
  include:
    - { rvm: 1.9.3, env: rack=1.4.0  }
    - { rvm: 1.8.7, env: tilt=master }
    - { rvm: 1.9.3, env: rack=master }
    - { rvm: 1.9.3, env: tilt=master }
  allow_failures:
    - env: tilt=master
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head
